### PR TITLE
Update test_image.py

### PR DESCRIPTION
**Pull request by nisargshah1999**
Update code for calculating inference time and FPS

### CODE REVIEW

**Comment by Lornatang** [comment]
This does not reflect the speed of GPU, and it doesn't make sense to do so.

**Comment by nisargshah1999** [comment]
This is not to calculate the speed of the model, it is to calculate the inference speed of prediction in FPS and sec. for particular GPU

**Comment by Lornatang** [comment]
To be sure, in a single sample, the inference speed of GPU model is similar to that of CPU.

**Comment by Lornatang** [comment]
@nisargshah1999 Sorry, I can't merge this right now.

**Pull request closed without merging**
